/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sim3;

import com.mycompany.practicab.Form;
import com.mycompany.practicab.PracticaB;
import com.mycompany.sim1.Simulador_memoria;
import com.mycompany.sim2.FormSIM2;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class FORM_SIM3 extends javax.swing.JFrame {
    private Lienzo dibujo = new Lienzo();
    public DefaultTableModel modelo;
    /**
     * Creates new form FORM_SIM3
     */
    public FORM_SIM3() {
        initComponents();
        dibujo.Dibujar();
        add(dibujo);
        buttonGroup1.add(jRadioButton1);
        buttonGroup1.add(jRadioButton2);
        buttonGroup1.add(jRadioButton3);
        buttonGroup1.add(jRadioButton4);
        buttonGroup1.add(jRadioButton5);
        buttonGroup1.add(jRadioButton6);
        this.modelo=(DefaultTableModel)table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        txtC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        lb6 = new javax.swing.JLabel();
        lb7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Peticiones"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("FCFS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("SSTF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("SCAN");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("C-SCAN");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jRadioButton5.setText("LOOK");

        jRadioButton6.setText("C-LOOK");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        txtC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCActionPerformed(evt);
            }
        });

        jLabel1.setText("CABEZAL");

        jButton2.setText("VER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lb.setText("PROMEDIO: ");

        lb1.setText("FCFS: ");

        lb2.setText("SSTF:");

        lb3.setText("SCAN:");

        lb4.setText("C-SCAN: ");

        lb5.setText("LOOK: ");

        lb6.setText("C-LOOK: ");

        lb7.setText("MEJOR: ");

        jButton4.setText("CALCULAR MEJOR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jMenu1.setText("MENU");

        jMenuItem1.setText("MENU SIMULADOR MEMORIA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("MENU ASIGNACION DE ARCHIVOS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("MENU LRU-FIFO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("SALIR");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb1)
                    .addComponent(lb4))
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb2)
                    .addComponent(lb5))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton1)
                                            .addComponent(jRadioButton2)
                                            .addComponent(jRadioButton3))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(28, 28, 28)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton4)
                                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(lb))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb6)
                        .addGap(76, 76, 76)
                        .addComponent(lb7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(lb))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1)
                    .addComponent(lb3)
                    .addComponent(lb2)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb4)
                    .addComponent(lb5)
                    .addComponent(lb6)
                    .addComponent(lb7))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void txtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dibujo.peticiones=new ArrayList<Integer>();
        
        String asignacion=JOptionPane.showInputDialog("Ingrese las peticiones separadas por espacios");
            
        String[] cadRef=asignacion.split(" ");
        int[] cadR=new int[cadRef.length];
        for(int i=0; i<cadRef.length; i++)
            dibujo.peticiones.add(Integer.parseInt(cadRef[i]));
        llenarTabla();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int c=Integer.parseInt(txtC.getText());
        dibujo.setCabezal(c);
        ArrayList<Integer> resultado=new ArrayList<Integer>();
        
        if(jRadioButton1.isSelected()){
            for(int x: dibujo.peticiones)
                resultado.add(x);
            dibujo.setResultado(resultado);
        }else if(jRadioButton2.isSelected()){
            
            ArrayList<Integer> copia=new ArrayList<Integer>();
            for(int x: dibujo.peticiones){
                copia.add(x);
            }
            
            int masCercana=0;
            int x=0;
            int actual=c;
            int indice=0;
            
            while(!copia.isEmpty()){
                indice=0;
                masCercana=copia.get(0);
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(Math.abs(actual-masCercana)>Math.abs(actual-x)){
                        masCercana=x;
                        indice=i;
                    }   
                }
                //System.out.println("MAS CERCANA: "+masCercana);
                resultado.add(masCercana);
                copia.remove(indice);
                actual=masCercana;
            }
            dibujo.setResultado(resultado);
            
        }else if(jRadioButton3.isSelected()){
            ArrayList<Integer> copia=new ArrayList<Integer>();
            
            for(int x: dibujo.peticiones){
                copia.add(x);
            }
            int movil=c;
            int orientacion=1;
            int x=0;
            while(!copia.isEmpty()){
                
                if(movil>199){
                    orientacion=orientacion*(-1);
                    resultado.add(199);
                }
                if(movil<=0){
                    orientacion=orientacion*(-1);
                    resultado.add(0);
                }
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x){
                        resultado.add(x);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                
                movil+=orientacion;
            }
            resultado.add(0);
            dibujo.setResultado(resultado);
        }else if(jRadioButton4.isSelected()){
            ArrayList<Integer> copia=new ArrayList<Integer>();
            
            for(int x: dibujo.peticiones){
                copia.add(x);
            }
            int movil=c;
            int x=0;
            while(!copia.isEmpty()){
                
                if(movil>199){
                    movil=0;
                    resultado.add(199);
                    resultado.add(0);
                }
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x){
                        resultado.add(x);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                movil+=1;
            }
            dibujo.setResultado(resultado);
        }else if(jRadioButton5.isSelected()){
            ArrayList<Integer> copia=new ArrayList<Integer>();
            
            for(int x: dibujo.peticiones){
                copia.add(x);
            }
            int movil=c;
            int orientacion=1;
            int x=0;
            while(!copia.isEmpty()){
                
                if(movil<=0 ||movil>199)
                    orientacion=orientacion*(-1);
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x){
                        resultado.add(x);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                
                movil+=orientacion;
            }
            dibujo.setResultado(resultado);
        }else if(jRadioButton6.isSelected()){
            ArrayList<Integer> copia=new ArrayList<Integer>();
            
            for(int x: dibujo.peticiones){
                copia.add(x);
            }
            int movil=c;
            int x=0;
            while(!copia.isEmpty()){
                if(movil>199)
                   movil=0; 
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x){
                        resultado.add(x);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                
                movil+=1;
            }
            dibujo.setResultado(resultado);
        }
        double promedio=0;
        promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        lb.setText("PROMEDIO: "+String.format("%.2f", promedio));
        dibujo.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        PracticaB aux=new PracticaB();
                aux.interfaz.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Simulador_memoria lruMenu=new Simulador_memoria();
                lruMenu.setVisible(true);
                //frame.dispose();
                dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FormSIM2 lruMenu=new FormSIM2();
                lruMenu.setVisible(true);        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dibujo.promedio=new ArrayList<Double>();
        double promedio=0;
        int c=Integer.parseInt(txtC.getText());
        ArrayList<Integer> resultado=new ArrayList<Integer>();
        ArrayList<Integer> copia=new ArrayList<Integer>();
        
        for(int x: dibujo.peticiones)
                resultado.add(x);
        
        promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        dibujo.promedio.add(promedio);
        
        lb1.setText("FCFS: "+ String.format("%.2f", promedio));
        promedio=0;
        copia=new ArrayList<Integer>();
        resultado=new ArrayList<Integer>();
        
        for(int x: dibujo.peticiones){
                copia.add(x);
            }
            
            int masCercana=0;
            int x=0;
            int actual=c;
            int indice=0;
            
            while(!copia.isEmpty()){
                indice=0;
                masCercana=copia.get(0);
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(Math.abs(actual-masCercana)>Math.abs(actual-x)){
                        masCercana=x;
                        indice=i;
                    }   
                }
                //System.out.println("MAS CERCANA: "+masCercana);
                resultado.add(masCercana);
                copia.remove(indice);
                actual=masCercana;
            }
            
            promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        dibujo.promedio.add(promedio);
        
        lb2.setText("SSTF: "+ String.format("%.2f", promedio));
        promedio=0;
        copia=new ArrayList<Integer>();
        resultado=new ArrayList<Integer>();
        
        for(int x1: dibujo.peticiones){
                copia.add(x1);
            }
            int movil=c;
            int orientacion=1;
            int x1=0;
            while(!copia.isEmpty()){
                
                if(movil>199){
                    orientacion=orientacion*(-1);
                    resultado.add(199);
                }
                if(movil<=0){
                    orientacion=orientacion*(-1);
                    resultado.add(0);
                }
                for(int i=0;i<copia.size();i++){
                    x1=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x1){
                        resultado.add(x1);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                
                movil+=orientacion;
            }
            resultado.add(0);
            
            promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        dibujo.promedio.add(promedio);
        
        lb3.setText("SCAN: "+ String.format("%.2f", promedio));
        promedio=0;
        copia=new ArrayList<Integer>();
        resultado=new ArrayList<Integer>();
            
        
        for(int x2: dibujo.peticiones){
                copia.add(x2);
            }
            movil=c;
            int x2=0;
            while(!copia.isEmpty()){
                
                if(movil>199){
                    movil=0;
                    resultado.add(199);
                    resultado.add(0);
                }
                for(int i=0;i<copia.size();i++){
                    x2=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x2){
                        resultado.add(x2);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                movil+=1;
            }
            
            promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        dibujo.promedio.add(promedio);
        
        lb4.setText("C-SCAN: "+ String.format("%.2f", promedio));
        promedio=0;
        copia=new ArrayList<Integer>();
        resultado=new ArrayList<Integer>();
        
        for(int x5: dibujo.peticiones){
                copia.add(x5);
            }
            movil=c;
            orientacion=1;
            x=0;
            while(!copia.isEmpty()){
                
                if(movil<=0 ||movil>199)
                    orientacion=orientacion*(-1);
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    if(movil==x){
                        resultado.add(x);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                
                movil+=orientacion;
            }
        
        promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        dibujo.promedio.add(promedio);
        
        lb5.setText("LOOK: "+ String.format("%.2f", promedio));
        promedio=0;
        copia=new ArrayList<Integer>();
        resultado=new ArrayList<Integer>();
        
           for(int x4: dibujo.peticiones){
                copia.add(x4);
            }
            movil=c;
            x=0;
            while(!copia.isEmpty()){
                if(movil>199)
                   movil=0; 
                for(int i=0;i<copia.size();i++){
                    x=copia.get(i);
                    //System.out.println("actual-masCercana: "+(actual-masCercana));
                    //System.out.println("actual-val: "+(actual-x));
                    if(movil==x){
                        resultado.add(x);
                        copia.remove(i);
                        i-=1;
                    }   
                }
                movil+=1;
            }
        
        promedio=Math.abs(c-resultado.get(0));
        for(int i=0;i<resultado.size()-1;i++){
            promedio+=Math.abs(resultado.get(i)-resultado.get(i+1));
        }
        promedio=promedio/dibujo.peticiones.size();
        dibujo.promedio.add(promedio);
        lb6.setText("C-LOOK: "+ String.format("%.2f", promedio));
        
        double min=dibujo.promedio.get(0);
        indice=0;
        for(int j=1;j<dibujo.promedio.size();j++){
            if(dibujo.promedio.get(j)<min){
                min=dibujo.promedio.get(j);
                indice=j;
            }
        }
        String alg="";
        
        if(indice==0){
           alg="FCFS" ;
        }
        if(indice==1){
           alg="SSTF" ;
        }
        if(indice==2){
           alg="SCAN" ;
        }
        if(indice==3){
           alg="C-SCAN" ;
        }
        if(indice==4){
           alg="LOOK" ;
        }
        if(indice==5){
           alg="C-LOOK" ;
        }
        lb7.setText("MEJOR: "+alg+"("+String.format("%.2f", min)+")");
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_SIM3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_SIM3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_SIM3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_SIM3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_SIM3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JLabel lb6;
    private javax.swing.JLabel lb7;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtC;
    // End of variables declaration//GEN-END:variables

    public void llenarTabla(){
        modelo.setRowCount(0);
        String tipo="";
        for(int x: dibujo.peticiones){
            modelo.addRow(new Object[]{x});
            
        }
        
    }
}   
