/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.practicab;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;
import javax.swing.JTable;
import javax.swing.table.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableModel;
import com.mycompany.sim1.Simulador_memoria;
import com.mycompany.sim2.FormSIM2;
import com.mycompany.sim3.FORM_SIM3;
/**
 *
 * @author HP
 */
public class Form extends javax.swing.JFrame {
    public DefaultTableModel modelo;
    //JTable tabla=new JTable(modelo);
    
    
    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        contruyeVentana();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        txt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnFIFO = new javax.swing.JButton();
        btnLRU = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lbRazon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbRendimiento = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jScrollPane2.setViewportView(jScrollPane1);

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cadena de referencia");

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de marcos");

        btnFIFO.setText("FIFO");
        btnFIFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFIFOActionPerformed(evt);
            }
        });

        btnLRU.setText("LRU");
        btnLRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLRUActionPerformed(evt);
            }
        });

        jLabel3.setText("Razon de fallos:");

        lbRazon.setText("...");

        jLabel5.setText("Rendimiento:");

        lbRendimiento.setText("...");

        jMenu1.setText("MENU");

        jMenuItem1.setText("MENU SIM1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("MENU ASIGNACION DE ARCHIVOS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("MENU ASIGNACION DISCO");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("SALIR");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        menu.add(jMenu1);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(396, 396, 396)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(lbRazon))
                    .addComponent(lbRendimiento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(129, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnFIFO)
                                    .addComponent(btnLRU))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFIFO)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLRU)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbRazon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbRendimiento)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void btnFIFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFIFOActionPerformed
        // TODO add your handling code here:
        int[] cadR;
        String[] cadRef=txt1.getText().split(" ");
        int m=Integer.parseInt(txt2.getText());
        cadR=new int[cadRef.length];
        
        for(int i=0; i<cadRef.length; i++){
            cadR[i]=Integer.parseInt(cadRef[i]);
        }
        
        PracticaB.fifoG(cadR, m);
        
    }//GEN-LAST:event_btnFIFOActionPerformed

    private void btnLRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLRUActionPerformed
        // TODO add your handling code here:
        int[] cadR;
        String[] cadRef=txt1.getText().split(" ");
        int m=Integer.parseInt(txt2.getText());
        cadR=new int[cadRef.length];
        
        for(int i=0; i<cadRef.length; i++){
            cadR[i]=Integer.parseInt(cadRef[i]);
        }
        PracticaB.lruG(cadR, m);
        
    }//GEN-LAST:event_btnLRUActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Simulador_memoria lruMenu=new Simulador_memoria();
                lruMenu.setVisible(true);
                //frame.dispose();
                dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

               FormSIM2 lruMenu=new FormSIM2();
                lruMenu.setVisible(true);        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        FORM_SIM3 menu=new FORM_SIM3();
                menu.setVisible(true);
                this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }
    
    public void setDim(int x,int y){
        modelo=(DefaultTableModel)tabla.getModel();
        
        String[] columnNames =new String[x+1];
        columnNames[0]="Tiempo";
        for(int i=1;i<x+1;i++){
            columnNames[i]=Integer.toString(i);
        }
        
        modelo=new DefaultTableModel(columnNames,y+2);
        modelo.setValueAt("Referencia", 0, 0);
        for(int i=0;i<y;i++){
            modelo.setValueAt("M"+i, i+1, 0);
        }
        modelo.setValueAt("Fallo", y+1,0 );
        tabla.setModel(modelo);
       
        //tabla.setAutoResizeMode(AUTO_RESIZE_ALL_COLUMNS);
        //modelo.fireTableDataChanged();
        //tabla.getTableHeader().resizeAndRepaint();
        //tabla.setVisible(false);
        //tabla.setVisible(true);
        
        /*modelo=(DefaultTableModel)tabla.getModel();
        Object datos[];
        datos=new Object[x];
        
        TableColumn c = new TableColumn();
            c.setHeaderValue("Tiempo");
            //table.getColumnModel().addColumn(c);
            tabla.addColumn(c);
        
        for(int i=0;i<x;i++){
            c = new TableColumn();
            c.setHeaderValue(Integer.toString(i+1));
            //table.getColumnModel().addColumn(c);
            tabla.addColumn(c);
        }
        
        for(int j=0;j<=y;j++){
            for(int i=0;i<x;i++){
               datos[i]=new String("");
            }
             modelo.addRow(datos);
             
        }
        
       modelo.setValueAt("Referencia", 0, 0);
        modelo.setValueAt("m0", 1, 1);
        
        modelo.addColumn("Col1");
        modelo.addColumn("Col2");

        tabla.getColumnModel().getColumn(0).setHeaderValue("New Name");
        tabla.getTableHeader().resizeAndRepaint();
        this.add(tabla);*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFIFO;
    private javax.swing.JButton btnLRU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lbRazon;
    public javax.swing.JLabel lbRendimiento;
    private javax.swing.JMenuBar menu;
    public javax.swing.JTable tabla;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
    //private JMenu menu;
    private JMenuItem im1, im2, im3, im4,im5;
    private JMenuBar barramenu;

    public void contruyeVentana(){
        //JFrame frame = new JFrame();

        //Construimos el menu 
        //*******************************************************************************
        //menu= new JMenu("Opciones");
        barramenu = new JMenuBar();
        setJMenuBar(barramenu);
        barramenu.add(menu);
        /*im1= new JMenuItem("MENU SIM1");
        im2= new JMenuItem("Borrar datos");
        im3= new JMenuItem("Salir");
        im4= new JMenuItem("Informacion...");
        im5= new JMenuItem("MENU ASIGNACION DE ARCHIVOS");
        
        im1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Simulador_memoria lruMenu=new Simulador_memoria();
                lruMenu.setVisible(true);
                //frame.dispose();
                dispose();
            }
        });
        im2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        });
        im3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //frame.dispose();
                System.exit(0);
            }
        });
        im4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //JOptionPane.showMessageDialog(," Sistemas Operativos 2" );
            }
        });
        im5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               FormSIM2 lruMenu=new FormSIM2();
                lruMenu.setVisible(true);
                //frame.dispose();
            }
        });
        
        */
        //agregamos el menu
        //frame.add(barramenu);
        //this.add(frame);
           /*
        //agregamos los paneles al frame principal
        frame.add(dibujo);
        frame.add(panelIzquierdo,BorderLayout.WEST);
        frame.add(panelSuperior,BorderLayout.NORTH);

        //Configuramos el frame
        pack();
        frame.setTitle("Simulador Particiones");
        frame.setSize(1000, 700);           // tamano a la ventana (ancho, alto)
        frame.setLocationRelativeTo(null);  // centrar la ventana en la pantalla
        frame.setResizable(false);
        frame.setVisible(true);
        */
       // frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }
    
}
